### ISSUE TITLE
Use Source Maps in Mocha Tests

### ISSUE THREAD

**Issue by fredfortier** [krasimir/webpack-library-starter#46]
I tried to naively use this module in my mocha tests: https://github.com/evanw/node-source-map-support

Instead of referencing the line number in my source file, my error stack looks like this:
```
Error: not implemented
    at MyClass.myFunction (xxx-js/lib/webpack:/xxx-js/node_modules/core-js/modules/es6.reflect.prevent-extensions.js:2:1)
    at Context.<anonymous> (xxx-js/test/MyClass.spec.js:105:12)
```

**Comment by krasimir** [comment]
I migrated the library to use Jest. Sorry.
