### ISSUE TITLE
 Cannot find module 'babel-helper-builder-binary-assignment-operator-visitor'

### ISSUE THREAD

**Issue by zhangpenglink** [krasimir/webpack-library-starter#47]
```
ERROR in ./src/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module 'babel-helper-builder-binary-assignment-operator-visitor'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (E:\Demo\Rollup\github-1\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (E:\Demo\Rollup\github-1\node_modules\babel-plugin-transform-exponentiation-operator\lib\index.js:6:81)
    at Module._compile (E:\Demo\Rollup\github-1\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (E:\Demo\Rollup\github-1\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (E:\Demo\Rollup\github-1\node_modules\babel-preset-env\lib\available-plugins.js:35:40)
    at Module._compile (E:\Demo\Rollup\github-1\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (E:\Demo\Rollup\github-1\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (E:\Demo\Rollup\github-1\node_modules\babel-preset-env\lib\index.js:29:48)
    at Module._compile (E:\Demo\Rollup\github-1\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (E:\Demo\Rollup\github-1\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at requireModule (E:\Demo\Rollup\github-1\node_modules\@babel\core\lib\config\files\plugins.js:164:12)
    at loadPreset (E:\Demo\Rollup\github-1\node_modules\@babel\core\lib\config\files\plugins.js:82:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! webpack-library-starter@1.0.2 build: `webpack --env dev && webpack --env build && npm run test`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the webpack-library-starter@1.0.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zhangpeng\AppData\Roaming\npm-cache\_logs\2018-10-10T10_09_35_842Z-debug.log
```

OS：windows  64

The reason of the Babel compatibility

**Comment by krasimir** [comment]
The starter is migrated to the latest webpack and babel today. I can't reproduce this problem. Reopen if you experiencing the same with the latest version.
